fix: use latest changes in floxpkgs template
flox-examples/hello-rust pull request #5
Opened 2022-09-08 17:44 UTC by mkenigs

Helps https://github.com/flox/flox/issues/192

2022-09-09 08:41 UTC, ysndr requested changes

2022-09-09 08:41 UTC, ysndr commented on pkgs/default.nix
> +  cargoLock.lockFile = ../Cargo.lock;
please add the optional macos buildInputs (`libiconv` and `darwin.apple_sdk.frameworks.Security`)
anyone on macos trying to adapt this to something they are familiar with will trip over that

2022-09-09 08:41 UTC, ysndr commented on flake.nix
> +        self,
`self` is unused here

2022-09-09 15:24 UTC, mkenigs commented on pkgs/default.nix
> +  cargoLock.lockFile = ../Cargo.lock;
I would like to keep this as an example (everything is actually used) rather than a template (suggestions for what will likely be used), and right now this builds on macos. Would it be easy to add actual usage of something that depends on those things? I haven't packaged something in Rust before, so if it would be easy for you to add something?

2022-09-09 16:07 UTC, ysndr commented on pkgs/default.nix
> +  cargoLock.lockFile = ../Cargo.lock;
I don't think the intended use of this is that of a template no, but people will inevitably use this as a starting point.
Maybe we should even base the examples on top of the template

2022-09-09 16:09 UTC, mkenigs commented on pkgs/default.nix
> +  cargoLock.lockFile = ../Cargo.lock;
Right I just mean if people cargo cult this example, it would be nice if it was a little more full-fledged and actually depended on openssl or something. Maybe that's too complicated for a hello example though

2022-09-09 16:21 UTC, ysndr commented on pkgs/default.nix
> +  cargoLock.lockFile = ../Cargo.lock;
I can write a hello world server or something, something basic but not trivial

2022-09-09 16:25 UTC, mkenigs commented on pkgs/default.nix
> +  cargoLock.lockFile = ../Cargo.lock;
Not as familiar as I'd like 😆 Would be great if you could write it and I can review and maybe learn some things 😀

2022-09-15 19:42 UTC, samrose commented on flake.nix
> +        self,
addressed also here with [f83a833](https://github.com/flox-examples/hello-rust/pull/5/commits/f83a833a5ba2f5c2d90c7b7c687b639413e0f2d5)

2022-09-15 19:45 UTC, samrose approved these changes
This builds and works as it is.

2022-09-15 20:05 UTC, merged